### ISSUE TITLE
question

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/tbnmc-compliance-assessment-2022#5]
marcus, not urgent, just curious what this is referencing and why it is still pointing to prior RA years. https://github.com/tbep-tech/tbnmc-compliance-assessment-2022/blob/49ef48664f5c0f0fefbbddc7fd027e6f94a1e0cb/index.Rmd#L350

**Comment by fawda123** [comment]
The text after `#` is commented out and describes additional text you can feed to the table function.  The text will be entered in the far right column for NMC Actions 1, 2, 3, etc. if you need to replace the default.  It doesn't do anything in the current draft because it's commented, I just left it there as a placeholder if/when OTB water quality is in the red.

**Comment by emseabee** [comment]
got it. thanks for explaining it to me.
