### ISSUE TITLE
can i get a download to pdf or word function

### ISSUE THREAD

**Issue by emseabee** [tbep-tech/tbnmc-compliance-assessment-2022#7]
printing the html to pdf to submit the report is quirky

**Comment by fawda123** [comment]
Working on it - the challenge is having both an HTML and PDF format that work.  A lot of the table output has to be recoded, but not impossible.  I'm setting it up as a Quarto website with a button to download a PDF. 

![image](https://user-images.githubusercontent.com/3086881/222227558-ee147b30-68c5-4230-befd-87d3e8b69209.png)

**Comment by fawda123** [comment]
@emseabee got the page working now: https://tbep-tech.github.io/tbnmc-compliance-assessment-2022/

The pdf file can be accessed using the pdf button, top left: https://tbep-tech.github.io/tbnmc-compliance-assessment-2022/2022-TAMPA-BAY-REASONABLE-ASSURANCE-COMPLIANCE-ASSESSMENT-REPORT.pdf

As it stands, the page doesn't build automatically with changes because of some issue I can't figure out, but I'll revisit for the 2023 report.

**Comment by fawda123** [comment]
From ROpenSci slack: Maybe you have an older version of one of the packages used and a newer version introduced this issue that only happens in ci because the newest version is installed there? You can try to reproduce in a docker container with no installed latex packages? (or re/move you existing library)

**Comment by fawda123** [comment]
Issue seems to have resolved itself...
